// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIMSApi.Model;

namespace SIMSApi.Migrations
{
    [DbContext(typeof(SIMSContext))]
    partial class SIMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SIMSApi.Model.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("SIMSApi.Model.UserInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserFullName")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(N'FirstName')")
                        .HasMaxLength(100);

                    b.Property<int>("UserGender");

                    b.Property<string>("UserImageUrl");

                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(N'userName')")
                        .HasMaxLength(100);

                    b.Property<string>("UserPassword")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1234))")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserGender");

                    b.ToTable("UserInformation");
                });

            modelBuilder.Entity("SIMSApi.Model.UserInformation", b =>
                {
                    b.HasOne("SIMSApi.Model.UserInformation", "CreatedByNavigation")
                        .WithMany("InverseCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_UserInformation_UserInformation");

                    b.HasOne("SIMSApi.Model.UserInformation", "UpdatedByNavigation")
                        .WithMany("InverseUpdatedByNavigation")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_UserInformation_UserInformation1");

                    b.HasOne("SIMSApi.Model.Gender", "UserGenderNavigation")
                        .WithMany("UserInformation")
                        .HasForeignKey("UserGender")
                        .HasConstraintName("FK_UserInformation_Gender");
                });
#pragma warning restore 612, 618
        }
    }
}
